'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCategory
    Public Property CategoryID As Integer
    Public Property CategoryName As String

    Public Overridable Property tblProjectCategories As ICollection(Of tblProjectCategory) = New HashSet(Of tblProjectCategory)

End Class
