'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblFacility
    Public Property FacitityID As Integer
    Public Property FacitityName As String

    Public Overridable Property tblProjectFacilities As ICollection(Of tblProjectFacility) = New HashSet(Of tblProjectFacility)

End Class
