'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblProjectDate
    Public Property ProjectDatesID As Integer
    Public Property ProjectID As Integer
    Public Property ScheduledStartDate As Nullable(Of Date)
    Public Property ScheduledEndDate As Nullable(Of Date)
    Public Property ActualStartDate As Nullable(Of Date)
    Public Property ActualEndDate As Nullable(Of Date)
    Public Property RequestedDate As Nullable(Of Date)
    Public Property ContactedDate As Nullable(Of Date)
    Public Property ArchiveDate As Nullable(Of Date)

    Public Overridable Property tblProjectInformation As tblProjectInformation

End Class
