'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblProjectResource
    Public Property ConvertionID As Integer
    Public Property ResourceID As Integer
    Public Property ProjectID As Integer

    Public Overridable Property tblProjectInformation As tblProjectInformation
    Public Overridable Property tblResource As tblResource

End Class
